### ISSUE TITLE
Semantic Link Text

### ISSUE THREAD

**Issue by nelsonic** [dwyl/contributing#96]
@dwyl we **_really_ appreciate** getting **contributions** from the ***community***. ❤️  ✅ 

But we _often_ get contributions that end up requiring more work to "_fix_" than _necessary_...

> _I could link to **many** PRs where the (`new`) contributor has made an addition/change 
that takes more time for the reviewer to "remedy" (later) than if the reviewer 
simply closed the PR and applied the "correct" changes in the first place ... 
`this` is not the place/time to "rant" about people not reading/following the existing PR/Contributing guidelines, it is an **opportunity** to **improve communication** and learning for all future people/contributions!_

This is _not_ the fault of the person making the contribution, rather it's the _my_ fault for not **setting** appropriate ***expectations*** i.e. **communication _fail_**. 😞 

Not to "_pick_" on anyone in particular ... 
`this` _happens_ from-time-to-time but I tend to "_correct_" it with **PR _comments_**
instead of fixing it "_systematically_" with _better instructions_!

## The Issue

Links to content where the link text does not give the reader _any_ clue what the content is.

> this just came up (_again_) in a PR and I think we need to "_fix_" (_i.e. **prevent**_) it.
> see: [![image](https://user-images.githubusercontent.com/194400/27006777-348c6c70-4e35-11e7-93a0-c04204200448.png)](https://github.com/dwyl/learn-elm/pull/91/commits/7cac47a2b99f8f350cc6e21b654328e9b55ab47c#diff-04c6e90faac2675aa89e2176d2eec7d8R322)

## The _Downside(s)_ of _Non_-Semantic Link Text

There are **_several_ disadvantages** to having non-semantic link text, 
here are the "***Top 5 Reasons non-Semantic Link Text are Bad***":

+ ***Accessibility*** - Visually Impaired People have _no idea_ what the content of the link is ... 😞 
(_yes, screen readers do read out the URL of the link, but it's way better if we include **semantic**/**insightful** text describing **exactly** what the content is either in the link text or alt text ..._)
+ **Link Obfuscation** - (_Non Sight Impaired_) People cannot see the what the link is or determine if it's relevant/useful without _hovering_ over it.  
+ **Mobile Unfriendly** - a person on a mobile device cannot see the URL or infer the content of the link so it _forces_ them to click links, load page(s) (_wasting bandwidth_) just to see if the content is relevant ... sure, the mobile user can "_rely_" on the content writer to an extent to not to link to useless/irrelevant things but how does the Mobile user know if "this" link is to a **20Mb** **PDF** that is going to cost them $$$ to download on their connection? (_it might be relevant but downloading it on a 2G internet connection would be super lame!_)
+ **Search Engine Optimisation** (***SEO***) - search engines cannot assess the _relevance_ of the link or give "credit" to the content. 🕸 👎  see: https://moz.com/blog/the-anatomy-of-a-link
+ **Update Tracking** - if the link text is "here", "example" or "this" it's not possible for people to see when the link gets updated. 

## Why _Not_ Simply Use (Paste) the _Full_ URL?

I _prefer_ to simply _paste_ the _entire_ link in the body of the Markdown text 
_especially_ when the URL is reasonably semantic / human readable. 

For example: 
![image](https://user-images.githubusercontent.com/194400/27006516-6c3ca53e-4e2d-11e7-9ba6-ee5fd86e5e40.png)
If this person had simply written ["Screaming Architecture"](https://8thlight.com/blog/uncle-bob/2011/09/30/Screaming-Architecture.html) I would _probably_ not have clicked on it.
But the fact that the article was written by "Uncle Bob" (_who I briefly met @GRPN and highly respect!_) _immediately_ got my attention. 

> BTW: I'm a _huge_ fan of the way links have a "Click Count" on Elixir Forum 
e.g: https://elixirforum.com/t/phoenix-v1-3-0-rc-0-released/3947
![image](https://user-images.githubusercontent.com/194400/27006508-23ec35a6-4e2d-11e7-86c5-1c77f6f254c6.png)

## TODO

+ [ ] Decide _where_ we should put the instructions (_@iteles thoughts?_)

+ [ ] Write _clear_ beginner friendly instructions for people on how to create great links in:
  + [ ] Markdown files (_which will/are rendered to HTML_)
  + [ ] HTML `should` we be writing "Raw" HTML

+ [ ] Link to Authoritative/Relevant "Background Reading" e.g: 
  + Techniques for Web Content Accessibility Guidelines 1.0: https://www.w3.org/TR/WCAG10-HTML-TECHS/
  + Tips for Developers: https://www.sitepoint.com/15-rules-making-accessible-links
  + W3C Link Checker: https://validator.w3.org/checklink
  + Internal vs External HTML Links: https://www.khanacademy.org/computing/computer-programming/html-css/html-tags-continued/p/html-internal-links

> Note: I think the "how to make a good link" instruction/guide _could_ go in https://github.com/dwyl/learn-html5 ***or*** but **100% Open to Suggestions**! 👍 
> Also, this raises another (_un-related?_) question: `should` we be writing "Raw" HTML? or should we be writing Markdown and _converting_ it to AMP-compliant Accessible HTML?

**Comment by iteles** [comment]
I think that whether we put it in https://github.com/dwyl/learn-html5 or https://github.com/dwyl/learn-markdown, we can't really realistically expect that people will go through the whole tutorial if they think they already know those things, particularly if they are new to dwyl. It should _certainly_ be in one of those anyway. 

I would suggest that what we actually need is a checklist of things that reviewers will be looking out for (that checklist can link to the more content heavy learn-x repos) that we then add as a message to a PR template for all our repos.

**Comment by nelsonic** [comment]
@iteles a _checklist_ for content reviewers is a _really_ good idea! 😍 
The _reason_ we _can_ `expect` people to go through the "_whole tutorial_" is because we are going to _design_ the learning UX that way ... 😉  (_as discussed in the park ages ago #LearningOrganisation ..._)
